name: ExpenseFlow
description: "Personal Finance App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  get_it: ^8.2.0
  home_widget: ^0.8.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  

flutter:
  fonts: 
    - family: SEGOE_UI
      fonts:
        - asset: assets/fonts/SegoeUI-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/SegoeUI-Bold.ttf
          weight: 700
        - asset: assets/fonts/SegoeUI-Italic.ttf
          style: italic
        - asset: assets/fonts/SegoeUI-Regular.ttf
  uses-material-design: true
